# this is AIMCE
elements = ['air', 'fire', 'water', 'earth', 'pressure', 'land', 'heat', 'energy', 'stone', 'wall', 'house', 'village', 'city', 'lava', 'pond', 'sea', 'ocean', 'lake', 'sand', 'desert', 'beach', 'puddle', 'planet', 'sun', 'sky', 'atmosphere', 'rain', 'storm', 'cloud', 'solar system', 'space', 'continent', 'explosion', 'volcano', 'skyscraper', 'life', 'lightning', 'smoke', 'galaxy', 'clay', 'mud', 'jupiter', 'tornado', 'wave', 'mercury', 'galaxy cluster', 'mars', 'sound', 'brick', 'universe', 'dune', 'dust', 'gunpowder', 'sandstorm', 'bacteria', 'primordial soup', 'space station', 'salt', 'supernova', 'electricity', 'glass', 'glasses', 'sunglasses', 'aquarium', 'wind', 'star', 'island', 'telescope', 'solar cell', 'smog', 'pyramid', 'fog', 'mist', 'warmth', 'swim goggles', 'acid rain', 'venus', 'alien', 'chimney', 'microscope', 'ozone']
print(len(elements))

# this is my fully
elements = ['wave', 'continent', 'steam', 'skyscraper', 'sand', 'night', 'supernova', 'seagull', 'mars', 'sea', 'sun', 'prism', 'solar system', 'swim goggles', 'space', 'heat', 'soil', 'space station', 'salt', 'dust', 'double rainbow!', 'universe', 'chameleon', 'pond', 'aquarium', 'village', 'lizard', 'nest', 'egg', 'cloud', 'glass', 'smog', 'land', 'alien', 'water', 'ocean', 'planet', 'magic', 'frog', 'wall', 'explosion', 'jupiter', 'acid rain', 'rain', 'tornado', 'stone', 'galaxy cluster', 'dune', 'pressure', 'day', 'galaxy', 'bird', 'primordial soup', 'moon', 'city', 'beach', 'glasses', 'phoenix', 'gunpowder', 'sunglasses', 'fire', 'storm', 'mud', 'dragon', 'life', 'lake', 'desert', 'air', 'owl', 'roe', 'duck', 'paint', 'telescope', 'rainbow', 'atmosphere', 'pigeon', 'safety glasses', 'energy', 'sky', 'wind', 'puddle', 'sandstorm', 'ostrich', 'brick', 'house', 'meteor', 'hurricane', 'lightning', 'animal', 'crystal ball', 'meteoroid', 'star', 'fog', 'earth', 'vulture', 'mercury']
print(len(elements))


elements =  ['wave', 'continent', 'skyscraper', 'steam', 'night', 'sand', 'seagull', 'supernova', 'mars', 'sea', 'sun', 'prism', 'solar system', 'swim goggles', 'space', 'heat', 'soil', 'space station', 'salt', 'dust', 'double rainbow!', 'universe', 'chameleon', 'pond', 'aquarium', 'lizard', 'village', 'egg', 'nest', 'cloud', 'glass', 'smog', 'land', 'alien', 'water', 'planet', 'magic', 'ocean', 'frog', 'wall', 'explosion', 'jupiter', 'rain', 'acid rain', 'tornado', 'stone', 'galaxy cluster', 'dune', 'pressure', 'day', 'galaxy', 'bird', 'primordial soup', 'moon', 'city', 'beach', 'glasses', 'phoenix', 'gunpowder', 'sunglasses', 'fire', 'storm', 'mud', 'dragon', 'life', 'lake', 'desert', 'air', 'owl', 'roe', 'duck', 'paint', 'telescope', 'rainbow', 'atmosphere', 'pigeon', 'safety glasses', 'energy', 'sky', 'wind', 'puddle', 'sandstorm', 'ostrich', 'brick', 'house', 'meteor', 'hurricane', 'lightning', 'animal', 'crystal ball', 'meteoroid', 'star', 'fog', 'earth', 'vulture', 'mercury']
print(len(elements))


invenotry = ['continent', 'wave', 'steam', 'skyscraper', 'sand', 'night', 'supernova', 'mars', 'seagull', 'sea', 'sun', 'prism', 'solar system', 'swim goggles', 'space', 'heat', 'soil', 'space station', 'salt', 'dust', 'double rainbow!', 'universe', 'chameleon', 'pond', 'aquarium', 'village', 'lizard', 'nest', 'egg', 'cloud', 'glass', 'smog', 'land', 'alien', 'water', 'planet', 'magic', 'frog', 'ocean', 'wall', 'explosion', 'jupiter', 'acid rain', 'rain', 'tornado', 'stone', 'galaxy cluster', 'dune', 'day', 'pressure', 'galaxy', 'moon', 'bird', 'primordial soup', 'city', 'beach', 'glasses', 'gunpowder', 'phoenix', 'sunglasses', 'fire', 'storm', 'mud', 'dragon', 'life', 'lake', 'desert', 'air', 'owl', 'roe', 'duck', 'paint', 'telescope', 'rainbow', 'atmosphere', 'pigeon', 'safety glasses', 'energy', 'sky', 'wind', 'puddle', 'sandstorm', 'ostrich', 'brick', 'house', 'meteor', 'hurricane', 'lightning', 'animal', 'crystal ball', 'meteoroid', 'star', 'fog', 'earth', 'vulture', 'mercury']
print(len(invenotry))

invenotry=['wave', 'continent', 'steam', 'skyscraper', 'sand', 'night', 'supernova', 'mars', 'seagull', 'sea', 'sun', 'prism', 'solar system', 'swim goggles', 'space', 'heat', 'soil', 'space station', 'salt', 'dust', 'double rainbow!', 'universe', 'chameleon', 'pond', 'aquarium', 'village', 'lizard', 'nest', 'egg', 'cloud', 'smog', 'glass', 'alien', 'land', 'water', 'planet', 'ocean', 'frog', 'magic', 'wall', 'explosion', 'jupiter', 'acid rain', 'rain', 'tornado', 'stone', 'galaxy cluster', 'dune', 'pressure', 'day', 'galaxy', 'moon', 'bird', 'primordial soup', 'city', 'beach', 'glasses', 'phoenix', 'gunpowder', 'sunglasses', 'fire', 'storm', 'mud', 'dragon', 'life', 'lake', 'desert', 'air', 'roe', 'owl', 'duck', 'paint', 'telescope', 'rainbow', 'atmosphere', 'pigeon', 'safety glasses', 'energy', 'sky', 'wind', 'puddle', 'sandstorm', 'ostrich', 'brick', 'house', 'meteor', 'hurricane', 'lightning', 'animal', 'crystal ball', 'meteoroid', 'star', 'fog', 'earth', 'vulture', 'mercury']
print(len(invenotry))


inventory =['continent', 'wave', 'steam', 'skyscraper', 'sand', 'night', 'supernova', 'seagull', 'mars', 'sea', 'sun', 'prism', 'solar system', 'swim goggles', 'space', 'heat', 'soil', 'space station', 'salt', 'dust', 'double rainbow!', 'universe', 'chameleon', 'pond', 'aquarium', 'village', 'lizard', 'nest', 'egg', 'cloud', 'glass', 'smog', 'land', 'alien', 'water', 'planet', 'magic', 'ocean', 'frog', 'wall', 'explosion', 'jupiter', 'acid rain', 'rain', 'tornado', 'stone', 'galaxy cluster', 'dune', 'pressure', 'day', 'galaxy', 'bird', 'primordial soup', 'moon', 'city', 'beach', 'glasses', 'phoenix', 'gunpowder', 'sunglasses', 'fire', 'storm', 'mud', 'dragon', 'life', 'lake', 'desert', 'air', 'owl', 'roe', 'duck', 'paint', 'telescope', 'rainbow', 'atmosphere', 'pigeon', 'safety glasses', 'energy', 'sky', 'wind', 'puddle', 'sandstorm', 'ostrich', 'brick', 'house', 'meteor', 'hurricane', 'lightning', 'animal', 'crystal ball', 'meteoroid', 'star', 'fog', 'earth', 'vulture', 'mercury']
print(len(inventory))

invenotry =  ['wave', 'continent', 'steam', 'skyscraper', 'sand', 'night', 'supernova', 'seagull', 'mars', 'sea', 'sun', 'prism', 'solar system', 'swim goggles', 'space', 'heat', 'soil', 'space station', 'salt', 'dust', 'double rainbow!', 'universe', 'chameleon', 'pond', 'aquarium', 'village', 'lizard', 'nest', 'egg', 'cloud', 'glass', 'smog', 'land', 'alien', 'water', 'planet', 'magic', 'ocean', 'frog', 'wall', 'explosion', 'jupiter', 'acid rain', 'rain', 'tornado', 'stone', 'galaxy cluster', 'dune', 'pressure', 'day', 'galaxy', 'bird', 'primordial soup', 'moon', 'city', 'beach', 'glasses', 'phoenix', 'gunpowder', 'sunglasses', 'fire', 'storm', 'mud', 'dragon', 'life', 'lake', 'desert', 'air', 'owl', 'duck', 'roe', 'paint', 'telescope', 'rainbow', 'atmosphere', 'pigeon', 'safety glasses', 'energy', 'sky', 'wind', 'puddle', 'sandstorm', 'ostrich', 'brick', 'house', 'meteor', 'hurricane', 'lightning', 'animal', 'crystal ball', 'meteoroid', 'star', 'fog', 'earth', 'vulture', 'mercury']
print(len(invenotry))








